### PR TITLE
[DM-3747] Moving SNMP to cumulocity examples

### PR DESCRIPTION
**Pull request by dmajsag**
Description

SNMP is deprecated but we still have SNMP docs on our website. This has lead to confusion with presales and customers who thought this was still a product feature.

move everything related to the SNMP docs ([SNMP - Cumulocity IoT documentation](https://cumulocity.com/docs/protocol-integration/snmp/) ) to the examples repo where the code is. Don’t spend time on fixing links just move the docs for archival purposes. Create a readmy that explains that this functionality is deprecated an no longer supported by the product team.

Acceptance criterion
- Docs moved as described
- readme created as described

Information for Release Notes

### CODE REVIEW

**Review by bozhidardedov — APPROVED** [review]

**Review by dafkk — DISMISSED** [review]
Should you maybe put all this in protocol integration in a docs folder?

**Comment by dmajsag** [comment]
> Should you maybe put all this in protocol integration in a docs folder?

I have left the same structure as it was in the c8y-docs, all is placed in protocol integration I would leave it as it is , Beate what do you think? If needed I will move it

**Comment by BeateRixen** [comment]
> > Should you maybe put all this in protocol integration in a docs folder?
> 
> I have left the same structure as it was in the c8y-docs, all is placed in protocol integration I would leave it as it is , Beate what do you think? If needed I will move it

I leave it up to you how you want to structure the content in this repo. 

Anyway, this are only source files and the structure is hard to understand without the Hugo setup. Perhaps you link in the readme to the 2024 documentation which is probably the last release that includes this documentation? That would make reading easier.

For the ops documentation, I would probably also provide the latest PDF (also from 2024) for better readability.

**Review by dafkk — DISMISSED** [review]
It is fine like this also for better readability I would add folders for docs and docs-ops. For PDFs I don't think it is necessary as Philipp stated in the story that it is only for archive purposes and not to spend extra time fixing links and etc.

**Comment by dmajsag** [comment]
> It is fine like this also for better readability I would add folders for docs and docs-ops. For PDFs I don't think it is necessary as Philipp stated in the story that it is only for archive purposes and not to spend extra time fixing links and etc.

Added folders docs and docs-ops and moved around all the docs

**Review by dafkk — APPROVED** [review]

**Review by l2p- — APPROVED** [review]

**Pull request merged**
